### ISSUE TITLE
throws error when https_proxy environment is set

### ISSUE THREAD

**Issue by mknj** [robinjmurphy/https-agent#1]
node v8.10.0
    "https-agent": "^1.0.0"

```

$ cat bug.js 
process.env.https_proxy = 'http://badhostname:3128'
var httpsAgent = require('https-agent');
var fs = require('fs');
var https = require('https');
var agent = httpsAgent({ });

var options = {
  protocol: 'https:',
  hostname: 'www.google.com',
  port: 443,
  agent: agent
}

https.get(options, function (res) {
  res.on('data', function (data) {
    console.log(data.toString());
  });
});

$ node bug.js 
_http_client.js:127
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at TunnelingAgent.request (http.js:38:10)
    at TunnelingAgent.createSocket (node_modules/tunnel/lib/tunnel.js:116:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (node_modules/tunnel/lib/tunnel.js:188:41)
    at TunnelingAgent.addRequest (node_modules/tunnel/lib/tunnel.js:80:8)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
```

**Comment by mknj** [comment]
relates to https://github.com/koichik/node-tunnel/issues/12#issuecomment-172888322
